with open("script.txt", "r+", encoding='utf-8') as f:
    s = f.read()
    f.seek(0)
    f.truncate()
    # --------
    s = s.replace("رّ", "ر")
    s = s.replace("صُ", "ص")
    s = s.replace("كّ", "ك")
    s = s.replace("بّ", "ب")
    s = s.replace("يّ", "ي")
    s = s.replace("لّ", "ل")
    s = s.replace("نّ", "ن")
    s = s.replace("تّ", "ت")
    s = s.replace("أّ", "أ")
    s = s.replace("ثّ", "ث")
    s = s.replace("جّ", "ج")
    s = s.replace("حّ", "ح")
    s = s.replace("خّ", "خ")
    s = s.replace("دَّ", "د")
    s = s.replace("دَ", "د")
    s = s.replace("ذّ", "ذ")
    s = s.replace("زّ", "ز")
    s = s.replace("سّ", "س")
    s = s.replace("شّ", "ش")
    s = s.replace("ضّ", "ض")
    s = s.replace("طّ", "ط")
    s = s.replace("عّ", "ع")
    s = s.replace("غّ", "غ")
    s = s.replace("فّ", "ف")
    s = s.replace("قّ", "ق")
    s = s.replace("لّ", "ل")
    s = s.replace("مّ", "م")
    s = s.replace("هّ", "ه")
    s = s.replace("وّ", "و")
    s = s.replace("ظّ", "ظ")
    s = s.replace("اّ", "ا")
    s = s.replace(" ّ", "")
    # --------
    f.write(s)
    print("done")
